name: Sync Docs to Wiki

on:
  push:
    paths:
      - 'docs/**'
      - '.github/workflows/sync-wiki.yml'
    branches:
      - main
jobs:
  sync-wiki:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Clone the wiki repo
        run: |
          git clone https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}.wiki.git wiki

      - name: Sync docs
        run: |
          rsync -av --delete docs/ wiki/ --exclude .git/
          cd wiki
          git config user.name "github-actions"
          git config user.email "github-actions@users.noreply.github.com"
          git add .
          git commit -m "Sync documentation from /docs"
          git push
