name: Sync Docs to Wiki

on:
  push:
    paths:
      - 'docs/**'
      - '.github/workflows/sync-wiki.yml'
    branches:
      - main

jobs:
  sync-wiki:
    runs-on: ubuntu-latest
    steps:
        - uses: actions/checkout@master
        - name: Sync Wiki
          uses: joeizzard/action-wiki-sync@master
          with:
              username: gilmar-sales
              access_token: ${{ secrets.GITHUB_TOKEN }}
              wiki_folder: wiki
              commit_username: 'github-actions'
              commit_email: 'github-actions@users.noreply.github.com'
              commit_message: 'action: wiki sync'
